version: '3'

services:

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
        - "8080:8080"
    depends_on:
      - app
      - keycloak

  app:
    build: .
    volumes:
      - .:/home/node/app

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev #TODO: TROCAR PARA PRODUÇÃO
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.35-debian
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    security_opt:
      - seccomp:unconfined #TODO: REMOVER PARA PRODUÇÃO
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s